/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testcase_3 (
    input [2:0] values,
    output reg aout,
    output reg bout,
    output reg cout,
    output reg [2:0] abc
  );
  
  
  
  always @* begin
    abc = values;
    
    case (values[0+0-:1])
      1'h0: begin
        aout = 1'h0;
      end
      1'h1: begin
        aout = 1'h1;
      end
      default: begin
        aout = 1'h0;
      end
    endcase
    
    case (values[1+0-:1])
      1'h0: begin
        bout = 1'h0;
      end
      1'h1: begin
        bout = 1'h1;
      end
      default: begin
        bout = 1'h0;
      end
    endcase
    
    case (values[2+0-:1])
      1'h0: begin
        cout = 1'h0;
      end
      1'h1: begin
        cout = 1'h1;
      end
      default: begin
        cout = 1'h0;
      end
    endcase
  end
endmodule
